name: Deploy Tudu API (Production)

on:
  push:
    branches: ['master']
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      # Configuração SSH segura
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.API_TUDU_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host 89.116.73.70\n  StrictHostKeyChecking yes\n  LogLevel VERBOSE" > ~/.ssh/config
          ssh-keyscan -t ed25519 89.116.73.70 >> ~/.ssh/known_hosts

      # Build da API com validação rigorosa
      - name: Build da API
        working-directory: ./api
        run: |
          npm ci
          npm run build

          echo "=== Verificação do Build ==="
          if [ ! -f "dist/main.js" ]; then
            echo "❌ ERRO: main.js não encontrado em dist/"
            echo "Conteúdo de dist/:"
            ls -la dist/
            echo "Procurando arquivos JavaScript:"
            find dist/ -name "*.js"
            exit 1
          fi

          echo "✅ Build validado:"
          ls -la dist/main.js
          echo "ENTRY_POINT=main.js" >> $GITHUB_ENV

      # Deploy com verificação em tempo real
      - name: Sincronizar build
        run: |
          echo "📦 Listando arquivos locais:"
          ls -la ./api/dist/

          echo "🚀 Enviando arquivos..."
          rsync -avz \
            --progress \
            --delete \
            --chown=deployer:www-data \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./api/dist/ deployer@89.116.73.70:/var/www/tudu-api/

          echo "🔍 Verificação remota:"
          ssh -i ~/.ssh/deploy_key deployer@89.116.73.70 "ls -la /var/www/tudu-api/"

      # Configuração do PM2 com validação
      - name: Configurar PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 89.116.73.70
          username: deployer
          key: ${{ secrets.API_TUDU_SSH_KEY }}
          script: |
            echo "=== Validação pré-deploy ==="
            if [ ! -f "/var/www/tudu-api/main.js" ]; then
              echo "❌ ERRO CRÍTICO: main.js não encontrado no servidor!"
              echo "Conteúdo do diretório:"
              ls -la /var/www/tudu-api/
              echo "Arquivos existentes:"
              find /var/www/tudu-api -type f
              exit 1
            fi

            echo "=== Configurando ambiente ==="
            sudo mkdir -p /var/log/tudu-api
            sudo chown -R deployer:www-data /var/log/tudu-api /var/www/tudu-api

            echo "=== Instalando dependências ==="
            cd /var/www/tudu-api
            npm ci --production --ignore-scripts

            echo "=== Configurando PM2 ==="
            cat <<EOF > ecosystem.config.js
            module.exports = {
              apps: [{
                name: "tudu-api",
                script: "./main.js",
                cwd: "/var/www/tudu-api",
                env: {
                  NODE_ENV: "production",
                  PORT: 3000
                },
                error_file: "/var/log/tudu-api/error.log",
                out_file: "/var/log/tudu-api/out.log",
                time: true
              }]
            }
            EOF

            echo "=== Reiniciando serviço ==="
            pm2 delete tudu-api --silent || true
            pm2 start ecosystem.config.js
            pm2 save
            pm2 startup

            echo "=== Verificação final ==="
            echo "📌 Entrypoint: $(realpath /var/www/tudu-api/main.js)"
            echo "📝 Logs: /var/log/tudu-api/{out,error}.log"
            pm2 list
            echo "🔄 Última atualização: $(date +'%Y-%m-%d %H:%M:%S')"
