name: Deploy Tudu API (Production)

on:
  push:
    branches: ['master']
    paths:
      - 'api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      # Configuração SSH segura
      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.API_TUDU_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          echo -e "Host 89.116.73.70\n  StrictHostKeyChecking yes\n  LogLevel VERBOSE" > ~/.ssh/config
          ssh-keyscan -t ed25519 89.116.73.70 >> ~/.ssh/known_hosts

      # Build da API (se necessário)
      - name: Build da API
        working-directory: ./api
        run: |
          npm ci
          npm run build  # Ou o comando que gera a pasta dist
          echo "Build gerado em:"
          ls -lh dist/

      # Deploy dos arquivos compilados
      - name: Sincronizar build
        run: |
          rsync -avz --delete --chown=deployer:www-data \
            -e "ssh -i ~/.ssh/deploy_key" \
            ./api/dist/ deployer@89.116.73.70:/var/www/tudu-api/

      # Configuração do PM2
      - name: Gerenciar Processo PM2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 89.116.73.70
          username: deployer
          key: ${{ secrets.API_TUDU_SSH_KEY }}
          script: |
            echo "=== Estrutura de diretórios ==="
            sudo mkdir -p /var/log/tudu-api
            sudo chown deployer:www-data /var/log/tudu-api

            echo "=== Instalando dependências de produção ==="
            cd /var/www/tudu-api
            npm ci --production

            echo "=== Reiniciando serviço ==="
            if pm2 describe tudu-api > /dev/null; then
              pm2 reload tudu-api --update-env
            else
              pm2 start ecosystem.config.js --env production
              pm2 save
              pm2 startup
            fi

            echo "=== Status final ==="
            pm2 list
            echo "🔄 Última atualização: $(date +'%Y-%m-%d %H:%M:%S')"
